trigger:
  - main 

pool:
  name: 'MyAgent'

steps:
- task: PythonScript@0
  inputs:
    scriptSource: inline
    script: |
      pythonInterpreter: '/usr/bin/python3'

- task: PythonScript@0
  inputs:
    scriptSource: inline
    script: pytest

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results/*.xml'
    testRunTitle: 'Python Unit Tests'

 # - script: |
  #    python hello.py
   # displayName: 'Ejecutar script Python'

