trigger:
- main

pool:
  VmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- script: |
    flask --app app --version
  displayName: 'Verificar instalación de Flask'

- script: |
    pytest
  displayName: 'Ejecutar pruebas unitarias'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copiar archivos de salida'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artefactos'
  
- task: AzureWebApp@1
  inputs:
        azureSubscription: 'Test(d0af34f1-2d64-40d1-aa0e-9712f463b918)'
        appType: 'webAppLinux'
        appName: 'test-smart-talent'
        package: '$(build.DefaultWorkingDirectory)/**/*.zip'
        runtimeStack: 'PYTHON|3.12'
        startUpCommand: 'flask run'