trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Use Python 3.x'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: "curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -\nsudo apt-get install -y nodejs     \n"
  displayName: 'Install Node.js'

# Install dependency-check
- script: |
    repo="jhermann/dependency-check-py"
    python3 -m pip install -r "https://raw.githubusercontent.com/$repo/master/requirements.txt"
    python3 -m pip install "https://github.com/$repo/archive/master.zip#egg=dependency-check"
  displayName: 'Install dependency-check from source'

# Run dependency-check

- script: |
    dependency-check ./requirements.txt
  displayName: 'Run dependency-check'
- script: |
      pytest --cov=.
  displayName: 'Run tests'
