trigger:
- main

pool:
  name: 'MyAgent'

variables:
  buildConfiguration: 'Release'  # Configura la versión de build (Debug, Release, etc.)
  pythonVersion: '3.12'  # Especifica la versión de Python a utilizar

steps:

- script: |
    flask --app app --version
  displayName: 'Verificar instalación de Flask'

- script: |
    python3 install pytest
    pytest
  displayName: 'Ejecutar pruebas'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copiar archivos de salida'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artefactos'

