trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    installToolsWithPip: true
    customArguments: pytest
  displayName: 'Use Python 3.x'

- script: |
    echo "Hello World"
  displayName: 'Run a one-line script'

- script: |
   python -m pip list | grep pytest
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: "curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -\nsudo apt-get install -y nodejs     \n"
  displayName: 'Install Node.js'

# Install dependency-check
- script: |
    repo="jhermann/dependency-check-py"
    python3 -m pip install -r "https://raw.githubusercontent.com/$repo/master/requirements.txt"
    python3 -m pip install "https://github.com/$repo/archive/master.zip#egg=dependency-check"
  displayName: 'Install dependency-check from source'

# Run dependency-check

- script: |
    dependency-check ./requirements.txt
  displayName: 'Run dependency-check'
  
- script: |
    pip install -r requirements.txt
  displayName: 'Run test'
  
- script: | 
    echo "Hello World"
  displayName: 'Run dependency-check'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive app files'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/app.zip'
    artifactName: 'app'
  displayName: 'Publish app artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Test(d0af34f1-2d64-40d1-aa0e-9712f463b918)'
    appType: 'webAppLinux'
    appName: 'test-smart-talent'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    appSettings: '-SCM_DO_BUILD_DURING_DEPLOYMENT true'
  displayName: 'Deploy to Azure Web App'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'My Test Run'

