trigger:
  - main 

pool:
  name: 'MyAgent'

steps:
- script: |
    python3 -V
#    python3 -m venv linux
#    source linux/bin/activate
#    pip install flask
- task: AzureWebApp@1
  inputs:
        azureSubscription: 'Test(d0af34f1-2d64-40d1-aa0e-9712f463b918)'
        appType: 'webAppLinux'
        appName: 'test-smart-talent'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        runtimeStack: 'PYTHON|3.12'
        startUpCommand: 'flask run'
