trigger:
  - main 

pool:
  name: 'MyAgent'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12.3'

- task: PythonScript@0
  inputs:
    scriptSource: inline
    script: |
      print('Hola, como estas ?')
      import sys
      print(sys.version)

- task: PythonScript@0
  inputs:
    scriptSource: inline
    script: pytest

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results/*.xml'
    testRunTitle: 'Python Unit Tests'

 # - script: |
  #    python hello.py
   # displayName: 'Ejecutar script Python'

