trigger:
  - main 

pool:
  name: 'MyAgent'

steps:
  - powershell: |
      python -V
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World"

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
       # Write your commands here
      
        echo 'Hello world'