trigger:
- main

pool:
  name: 'MyAgent'

variables:
  buildConfiguration: 'Release'  # Configura la versión de build (Debug, Release, etc.)
  pythonVersion: '3.12'  # Especifica la versión de Python a utilizar

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
  displayName: 'Usar versión de Python'

- script: |
    pip install -r requirements.txt
  displayName: 'Instalar dependencias'

- script: |
    flask --app app --version
  displayName: 'Verificar instalación de Flask'

- script: |
    # Agregar aquí cualquier comando adicional, como ejecutar pruebas unitarias
    pytest
  displayName: 'Ejecutar pruebas'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copiar archivos de salida'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publicar artefactos'

